// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/person.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{0, 0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdated          *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Person) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=persons.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type PersonResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonResponse) Reset()         { *m = PersonResponse{} }
func (m *PersonResponse) String() string { return proto.CompactTextString(m) }
func (*PersonResponse) ProtoMessage()    {}
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{2}
}

func (m *PersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonResponse.Unmarshal(m, b)
}
func (m *PersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonResponse.Marshal(b, m, deterministic)
}
func (m *PersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonResponse.Merge(m, src)
}
func (m *PersonResponse) XXX_Size() int {
	return xxx_messageInfo_PersonResponse.Size(m)
}
func (m *PersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersonResponse proto.InternalMessageInfo

func (m *PersonResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetPersonDetails struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonDetails) Reset()         { *m = GetPersonDetails{} }
func (m *GetPersonDetails) String() string { return proto.CompactTextString(m) }
func (*GetPersonDetails) ProtoMessage()    {}
func (*GetPersonDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{3}
}

func (m *GetPersonDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonDetails.Unmarshal(m, b)
}
func (m *GetPersonDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonDetails.Marshal(b, m, deterministic)
}
func (m *GetPersonDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonDetails.Merge(m, src)
}
func (m *GetPersonDetails) XXX_Size() int {
	return xxx_messageInfo_GetPersonDetails.Size(m)
}
func (m *GetPersonDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonDetails proto.InternalMessageInfo

func (m *GetPersonDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DeletePerosonID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePerosonID) Reset()         { *m = DeletePerosonID{} }
func (m *DeletePerosonID) String() string { return proto.CompactTextString(m) }
func (*DeletePerosonID) ProtoMessage()    {}
func (*DeletePerosonID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{5}
}

func (m *DeletePerosonID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePerosonID.Unmarshal(m, b)
}
func (m *DeletePerosonID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePerosonID.Marshal(b, m, deterministic)
}
func (m *DeletePerosonID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePerosonID.Merge(m, src)
}
func (m *DeletePerosonID) XXX_Size() int {
	return xxx_messageInfo_DeletePerosonID.Size(m)
}
func (m *DeletePerosonID) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePerosonID.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePerosonID proto.InternalMessageInfo

func (m *DeletePerosonID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePersonResponse struct {
	IsDeleted            bool                 `protobuf:"varint,1,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeletePersonResponse) Reset()         { *m = DeletePersonResponse{} }
func (m *DeletePersonResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePersonResponse) ProtoMessage()    {}
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{6}
}

func (m *DeletePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePersonResponse.Unmarshal(m, b)
}
func (m *DeletePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePersonResponse.Marshal(b, m, deterministic)
}
func (m *DeletePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePersonResponse.Merge(m, src)
}
func (m *DeletePersonResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePersonResponse.Size(m)
}
func (m *DeletePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePersonResponse proto.InternalMessageInfo

func (m *DeletePersonResponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *DeletePersonResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("persons.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "persons.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "persons.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "persons.AddressBook")
	proto.RegisterType((*PersonResponse)(nil), "persons.PersonResponse")
	proto.RegisterType((*GetPersonDetails)(nil), "persons.GetPersonDetails")
	proto.RegisterType((*Empty)(nil), "persons.Empty")
	proto.RegisterType((*DeletePerosonID)(nil), "persons.DeletePerosonID")
	proto.RegisterType((*DeletePersonResponse)(nil), "persons.DeletePersonResponse")
}

func init() { proto.RegisterFile("pb/person.proto", fileDescriptor_a772b4d5200054a8) }

var fileDescriptor_a772b4d5200054a8 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x61, 0x8f, 0xd2, 0x4e,
	0x10, 0xc6, 0xa1, 0x07, 0xbd, 0x63, 0xe0, 0x80, 0x6c, 0xc8, 0xff, 0x5f, 0x6b, 0x2e, 0xe2, 0xbe,
	0x91, 0xc4, 0x58, 0x12, 0x2e, 0xd1, 0x68, 0x62, 0x0c, 0x08, 0x39, 0x89, 0x9e, 0x90, 0x8a, 0x31,
	0xf1, 0x0d, 0x29, 0xd7, 0xf1, 0x6c, 0x6c, 0xbb, 0x9b, 0xee, 0x62, 0xc2, 0xf7, 0xf3, 0x23, 0xf9,
	0x01, 0x4c, 0x77, 0x97, 0x8a, 0x45, 0x73, 0xef, 0x76, 0x66, 0x7e, 0xed, 0x3e, 0xf3, 0x3c, 0x0b,
	0x1d, 0xbe, 0x19, 0x72, 0xcc, 0x04, 0x4b, 0x3d, 0x9e, 0x31, 0xc9, 0xc8, 0xa9, 0xae, 0x84, 0xfb,
	0xe0, 0x96, 0xb1, 0xdb, 0x18, 0x87, 0xaa, 0xbd, 0xd9, 0x7e, 0x19, 0xca, 0x28, 0x41, 0x21, 0x83,
	0x84, 0x6b, 0x92, 0xfe, 0xb4, 0xc0, 0x5e, 0x2a, 0x98, 0x10, 0xa8, 0xa5, 0x41, 0x82, 0x4e, 0xb5,
	0x5f, 0x1d, 0x34, 0x7c, 0x75, 0x26, 0x6d, 0xb0, 0xa2, 0xd0, 0xb1, 0x54, 0xc7, 0x8a, 0x42, 0xd2,
	0x83, 0x3a, 0x26, 0x41, 0x14, 0x3b, 0x27, 0xaa, 0xa5, 0x0b, 0x72, 0x09, 0x36, 0xff, 0xca, 0x52,
	0x14, 0x4e, 0xad, 0x7f, 0x32, 0x68, 0x8e, 0xee, 0x7b, 0xe6, 0x7e, 0x4f, 0xff, 0xda, 0x5b, 0xe6,
	0xd3, 0xf7, 0xdb, 0x64, 0x83, 0x99, 0x6f, 0x50, 0xf2, 0x1c, 0xe0, 0x26, 0xc3, 0x40, 0x62, 0xb8,
	0x0e, 0xa4, 0x53, 0xef, 0x57, 0x07, 0xcd, 0x91, 0xeb, 0x69, 0xbd, 0xde, 0x5e, 0xaf, 0xb7, 0xda,
	0xeb, 0xf5, 0x1b, 0x86, 0x1e, 0x4b, 0xf2, 0x12, 0x5a, 0x71, 0x20, 0xe4, 0x7a, 0xcb, 0xc3, 0xbc,
	0xe3, 0xd8, 0x77, 0x7e, 0xdc, 0xcc, 0xf9, 0x8f, 0x1a, 0x77, 0x57, 0xd0, 0x3c, 0x10, 0x44, 0xfe,
	0x03, 0x3b, 0x55, 0x27, 0xb3, 0xb9, 0xa9, 0xc8, 0x13, 0xa8, 0xc9, 0x1d, 0x47, 0xb5, 0x7d, 0x7b,
	0x74, 0xef, 0xaf, 0x3b, 0xad, 0x76, 0x1c, 0x7d, 0x85, 0xd1, 0xc7, 0xd0, 0x28, 0x5a, 0x04, 0xc0,
	0xbe, 0x5e, 0x4c, 0xe6, 0xef, 0x66, 0xdd, 0x0a, 0x39, 0x83, 0xda, 0x9b, 0xc5, 0xf5, 0xac, 0x5b,
	0xcd, 0x4f, 0x9f, 0x16, 0xfe, 0xdb, 0xae, 0x45, 0x9f, 0x42, 0x73, 0x1c, 0x86, 0x19, 0x0a, 0x31,
	0x61, 0xec, 0x1b, 0x79, 0x04, 0x36, 0x47, 0xc6, 0xe3, 0xdc, 0xfc, 0xdc, 0xc0, 0x4e, 0xe9, 0x32,
	0xdf, 0x8c, 0xe9, 0x00, 0xda, 0xa6, 0x83, 0x82, 0xb3, 0x54, 0x60, 0xae, 0x5e, 0xc8, 0x40, 0x6e,
	0xc5, 0x5e, 0xbd, 0xae, 0x28, 0x85, 0xee, 0x15, 0x4a, 0x0d, 0x4f, 0x51, 0x06, 0x51, 0x2c, 0x4c,
	0x9a, 0xd5, 0x7d, 0x9a, 0xf4, 0x14, 0xea, 0xb3, 0x84, 0xcb, 0x1d, 0x7d, 0x08, 0x9d, 0x29, 0xc6,
	0x28, 0x71, 0x89, 0x19, 0x13, 0x2c, 0x9d, 0x4f, 0x8f, 0x58, 0x0e, 0xbd, 0x02, 0x39, 0xbc, 0xff,
	0x02, 0x20, 0x12, 0xeb, 0x50, 0x8d, 0x34, 0x7f, 0xe6, 0x37, 0x22, 0xa1, 0xd9, 0x30, 0x4f, 0xd9,
	0xcc, 0xf2, 0x94, 0xad, 0xbb, 0x53, 0x36, 0xf4, 0x58, 0x8e, 0x7e, 0x58, 0x70, 0xae, 0x2f, 0xfb,
	0x80, 0xd9, 0xf7, 0xe8, 0x06, 0xc9, 0x0b, 0x68, 0xbd, 0x56, 0x8f, 0xc0, 0xbc, 0xd8, 0xb2, 0x4d,
	0xee, 0xff, 0x65, 0xdf, 0x8c, 0x4a, 0x5a, 0x21, 0xaf, 0xa0, 0x53, 0xf2, 0x83, 0xfc, 0x8e, 0xb4,
	0xec, 0x94, 0x5b, 0xfe, 0x33, 0xad, 0x90, 0x67, 0x70, 0x7e, 0x85, 0x52, 0xa7, 0xa6, 0x42, 0x6b,
	0x17, 0x8c, 0x32, 0xd1, 0xed, 0x15, 0xf5, 0x41, 0xb4, 0xb4, 0x42, 0xe6, 0xd0, 0x3a, 0x74, 0x8e,
	0x38, 0x05, 0x57, 0xf2, 0xdc, 0xbd, 0x38, 0x9e, 0xfc, 0xb9, 0xc4, 0x08, 0x5a, 0xfa, 0x11, 0xff,
	0xcb, 0x80, 0x63, 0xdd, 0x93, 0xda, 0x67, 0x8b, 0x6f, 0x36, 0xb6, 0xf2, 0xfa, 0xf2, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xae, 0xa2, 0xd0, 0x43, 0x2b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	CreatePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*PersonResponse, error)
	GetPersonDetail(ctx context.Context, in *GetPersonDetails, opts ...grpc.CallOption) (*Person, error)
	GetAddresBook(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AddressBook, error)
	DeletePerson(ctx context.Context, in *DeletePerosonID, opts ...grpc.CallOption) (*DeletePersonResponse, error)
	UpdatePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) CreatePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*PersonResponse, error) {
	out := new(PersonResponse)
	err := c.cc.Invoke(ctx, "/persons.PersonService/CreatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) GetPersonDetail(ctx context.Context, in *GetPersonDetails, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/persons.PersonService/GetPersonDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) GetAddresBook(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AddressBook, error) {
	out := new(AddressBook)
	err := c.cc.Invoke(ctx, "/persons.PersonService/GetAddresBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) DeletePerson(ctx context.Context, in *DeletePerosonID, opts ...grpc.CallOption) (*DeletePersonResponse, error) {
	out := new(DeletePersonResponse)
	err := c.cc.Invoke(ctx, "/persons.PersonService/DeletePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) UpdatePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/persons.PersonService/UpdatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	CreatePerson(context.Context, *Person) (*PersonResponse, error)
	GetPersonDetail(context.Context, *GetPersonDetails) (*Person, error)
	GetAddresBook(context.Context, *Empty) (*AddressBook, error)
	DeletePerson(context.Context, *DeletePerosonID) (*DeletePersonResponse, error)
	UpdatePerson(context.Context, *Person) (*Person, error)
}

// UnimplementedPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServiceServer struct {
}

func (*UnimplementedPersonServiceServer) CreatePerson(ctx context.Context, req *Person) (*PersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePerson not implemented")
}
func (*UnimplementedPersonServiceServer) GetPersonDetail(ctx context.Context, req *GetPersonDetails) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonDetail not implemented")
}
func (*UnimplementedPersonServiceServer) GetAddresBook(ctx context.Context, req *Empty) (*AddressBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddresBook not implemented")
}
func (*UnimplementedPersonServiceServer) DeletePerson(ctx context.Context, req *DeletePerosonID) (*DeletePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePerson not implemented")
}
func (*UnimplementedPersonServiceServer) UpdatePerson(ctx context.Context, req *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePerson not implemented")
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persons.PersonService/CreatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).CreatePerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_GetPersonDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPersonDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persons.PersonService/GetPersonDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPersonDetail(ctx, req.(*GetPersonDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_GetAddresBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetAddresBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persons.PersonService/GetAddresBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetAddresBook(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_DeletePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePerosonID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).DeletePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persons.PersonService/DeletePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).DeletePerson(ctx, req.(*DeletePerosonID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_UpdatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).UpdatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persons.PersonService/UpdatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).UpdatePerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "persons.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _PersonService_CreatePerson_Handler,
		},
		{
			MethodName: "GetPersonDetail",
			Handler:    _PersonService_GetPersonDetail_Handler,
		},
		{
			MethodName: "GetAddresBook",
			Handler:    _PersonService_GetAddresBook_Handler,
		},
		{
			MethodName: "DeletePerson",
			Handler:    _PersonService_DeletePerson_Handler,
		},
		{
			MethodName: "UpdatePerson",
			Handler:    _PersonService_UpdatePerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/person.proto",
}
